// Code generated by go generate;
package quiz

import (
	"flag"

	"github.com/3d0c/cli/pkg"
	"github.com/3d0c/quiz/pkg/rpc"
)

type match struct {
	*cli.General

	addr     string
	endpoint string
}

func init() {
	cli.Register("quiz.match", &match{General: &cli.General{}})
}

func (cmd *match) Register(f *flag.FlagSet) {
	cmd.General.Register(f)
	f.StringVar(&cmd.addr, "addr", "127.0.0.1:5560", "quiz server location")
}

func (cmd *match) Description() string {
	return `
Description:
	Compare your score to others.

Examples:
	; show comparision
	q-client quiz.match

	; optionally define quiz server
	q-client quiz.match -addr=192.168.0.10:5560
	`
}

func (cmd *match) Process() error {
	cmd.endpoint = "http://" + cmd.addr + "/score" + "/" + key() + "/match"
	return nil
}

func (cmd *match) Run(f *flag.FlagSet) ([]byte, error) {
	return rpc.Get(cmd.endpoint, nil)
}
