// Code generated by go generate;
package quiz

import (
	"flag"

	"github.com/3d0c/cli/pkg"
	"github.com/3d0c/quiz/pkg/rpc"
)

type questions struct {
	*cli.General

	addr     string
	endpoint string
}

func init() {
	cli.Register("quiz.questions", &questions{General: &cli.General{}})
}

func (cmd *questions) Register(f *flag.FlagSet) {
	cmd.General.Register(f)
	f.StringVar(&cmd.addr, "addr", "127.0.0.1:5560", "quiz server location")
}

func (cmd *questions) Description() string {
	return `
Description:
	List QUIZ questions.

Examples:
	; list quiz questions
	q-client quiz.questions

	; optionally define quiz server
	q-client quiz.questions -addr=192.168.0.10:5560
	`
}

func (cmd *questions) Process() error {
	cmd.endpoint = "http://" + cmd.addr + "/questions" + "/" + key()
	return nil
}

func (cmd *questions) Run(f *flag.FlagSet) ([]byte, error) {
	return rpc.Get(cmd.endpoint, nil)
}
